project:
  type: website

website:
  title: "balloon-defense"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# Only compute R/Python lines on `quarto render`
# This is required for CI & Pages deployment
execute:
  freeze: auto
